# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=2047, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data utworzenia')),
            ],
        ),
        migrations.AddField(
            model_name='shorturl',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='short_url.Url', verbose_name='Pierwotny url'),
        ),
    ]
